"use client";

import { useState } from 'react';

export default function TestLLMPage() {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedCode, setGeneratedCode] = useState('');
  const [stlUrl, setStlUrl] = useState('');
  const [error, setError] = useState('');

  const generateModel = async () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    setError('');
    setGeneratedCode('');
    setStlUrl('');

    try {
      // Step 1: Generate JSCAD code from LLM
      console.log('🔍 DEBUG: Starting LLM generation for prompt:', prompt);
      
      const chatId = crypto.randomUUID();
      const messageId = crypto.randomUUID();
      
      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          id: chatId,
          message: {
            id: messageId,
            role: 'user',
                          parts: [
                {
                  type: 'text',
                  text: `Generate JSCAD code for: ${prompt}. Only return the JavaScript code, no explanations. DO NOT use import statements - all JSCAD functions (cube, sphere, cylinder, etc.) are already available. Define a main() function with no parameters.`
                }
              ]
          }
        })
      });

      console.log('🔍 DEBUG: Chat API response status:', response.status);

      if (!response.ok) {
        const errorText = await response.text();
        console.log('🔍 DEBUG: Chat API error response:', errorText);
        throw new Error(`Failed to generate code: ${response.status} ${response.statusText}`);
      }

      // Handle streaming response
      const reader = response.body?.getReader();
      if (!reader) {
        throw new Error('No response body');
      }

      let jscadCode = '';
      let isComplete = false;
      let finalCode = '';

      while (!isComplete) {
        const { done, value } = await reader.read();
        
        if (done) {
          isComplete = true;
          break;
        }

        const chunk = new TextDecoder().decode(value);
        console.log('🔍 DEBUG: Received chunk:', chunk);

        // Parse SSE format
        const lines = chunk.split('\n');
        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6));
              console.log('🔍 DEBUG: Parsed data:', data);
              
              if (data.type === 'text-delta' && data.textDelta) {
                jscadCode += data.textDelta;
              } else if (data.type === 'data-codeDelta' && data.data) {
                // This is the complete code, not a delta
                finalCode = data.data;
              }
            } catch (e) {
              // Ignore parsing errors for incomplete JSON
            }
          }
        }
      }

      // Use the final code if available, otherwise use the accumulated text
      const finalJscadCode = finalCode || jscadCode;

      console.log('🔍 DEBUG: Final JSCAD code from LLM:', finalJscadCode);
      
      if (!finalJscadCode.trim()) {
        throw new Error('No JSCAD code generated by LLM');
      }

      setGeneratedCode(finalJscadCode);

      // Step 2: Generate STL from the JSCAD code
      console.log('🔍 DEBUG: Sending JSCAD code to STL API');
      
      const stlResponse = await fetch('/api/stl/test', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ code: finalJscadCode })
      });

      console.log('🔍 DEBUG: STL API response status:', stlResponse.status);

      if (!stlResponse.ok) {
        const errorData = await stlResponse.json();
        console.log('🔍 DEBUG: STL API error response:', errorData);
        throw new Error(errorData.error || 'Failed to generate STL');
      }

      const stlBlob = await stlResponse.blob();
      console.log('🔍 DEBUG: STL blob size:', stlBlob.size);
      
      const url = URL.createObjectURL(stlBlob);
      setStlUrl(url);

    } catch (err) {
      console.log('🔍 DEBUG: Caught error:', err);
      setError(err instanceof Error ? err.message : 'An error occurred');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div style={{ fontFamily: 'Arial, sans-serif', margin: '20px', maxWidth: '800px', marginLeft: 'auto', marginRight: 'auto' }}>
      <h1>🧪 LLM → JSCAD → STL Test</h1>
      
      <div style={{ marginBottom: '20px' }}>
        <label htmlFor="prompt" style={{ display: 'block', marginBottom: '8px', fontWeight: 'bold' }}>
          Describe what you want to create:
        </label>
        <textarea
          id="prompt"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g., Create a simple cube with a hole in the middle"
          style={{ 
            width: '100%', 
            height: '80px', 
            padding: '10px',
            border: '1px solid #ccc',
            borderRadius: '4px',
            fontSize: '14px'
          }}
        />
      </div>

      <button
        onClick={generateModel}
        disabled={isGenerating || !prompt.trim()}
        style={{
          padding: '12px 24px',
          background: isGenerating ? '#ccc' : '#007bff',
          color: 'white',
          border: 'none',
          borderRadius: '4px',
          cursor: isGenerating ? 'not-allowed' : 'pointer',
          fontSize: '16px',
          marginBottom: '20px'
        }}
      >
        {isGenerating ? '🔄 Generating...' : '🚀 Generate Model'}
      </button>

      {error && (
        <div style={{
          padding: '12px',
          background: '#f8d7da',
          color: '#721c24',
          border: '1px solid #f5c6cb',
          borderRadius: '4px',
          marginBottom: '20px'
        }}>
          ❌ Error: {error}
        </div>
      )}

      {generatedCode && (
        <div style={{ marginBottom: '20px' }}>
          <h3>Generated JSCAD Code:</h3>
          <pre style={{
            background: '#f8f9fa',
            padding: '15px',
            border: '1px solid #dee2e6',
            borderRadius: '4px',
            overflow: 'auto',
            fontSize: '12px',
            maxHeight: '200px'
          }}>
            {generatedCode}
          </pre>
        </div>
      )}

      {stlUrl && (
        <div style={{
          padding: '15px',
          background: '#d4edda',
          color: '#155724',
          border: '1px solid #c3e6cb',
          borderRadius: '4px',
          marginBottom: '20px'
        }}>
          <h3>✅ STL File Generated!</h3>
          <a
            href={stlUrl}
            download="generated-model.stl"
            style={{
              display: 'inline-block',
              background: '#28a745',
              color: 'white',
              padding: '10px 20px',
              textDecoration: 'none',
              borderRadius: '4px',
              marginTop: '10px'
            }}
          >
            📥 Download STL File
          </a>
        </div>
      )}

      <div style={{ marginTop: '30px', padding: '15px', background: '#f8f9fa', borderRadius: '4px' }}>
        <h4>💡 Try these examples:</h4>
        <ul style={{ margin: '0', paddingLeft: '20px' }}>
          <li>"Create a simple cube with size 10"</li>
          <li>"Make a sphere with radius 5"</li>
          <li>"Generate a cylinder with radius 3 and height 8"</li>
          <li>"Create a cube with a cylindrical hole through the center"</li>
          <li>"Make a torus (donut shape) with inner radius 2 and outer radius 5"</li>
        </ul>
        <p style={{ marginTop: '10px', fontSize: '12px', color: '#666' }}>
          <strong>Note:</strong> This now uses the actual LLM to generate JSCAD code based on your prompt!
        </p>
      </div>
    </div>
  );
} 